name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    uses: sxzz/workflows/.github/workflows/release.yml@e3b122062c0844efea9328bd56c06ac337d72bc7 # main
    with:
      publish: true
    permissions:
      contents: write
      id-token: write
